### ISSUE TITLE
Launching MapActivity crash

### ISSUE THREAD

**Issue by kozych** [michalmobi/PatientAssistant#55]

**Comment by kozych** [comment]
FATAL EXCEPTION: main
                                                                                                    Process: com.example.patientassistant, PID: 7504
                                                                                                    java.lang.NullPointerException: Attempt to invoke virtual method 'double android.location.Location.getLatitude()' on a null object reference
                                                                                                    	at com.example.patientassistant.View.MapActivity$getLastLocationAndAnimateCamera$1.invoke(MapActivity.kt:129)
                                                                                                    	at com.example.patientassistant.View.MapActivity$getLastLocationAndAnimateCamera$1.invoke(MapActivity.kt:128)
                                                                                                    	at com.example.patientassistant.View.MapActivity.getLastLocationAndAnimateCamera$lambda$3(MapActivity.kt:128)
                                                                                                    	at com.example.patientassistant.View.MapActivity.$r8$lambda$OM16TbTD65yoAy6d_IPiVDT2W8o(Unknown Source:0)
                                                                                                    	at com.example.patientassistant.View.MapActivity$$ExternalSyntheticLambda2.onSuccess(Unknown Source:2)
                                                                                                    	at com.google.android.gms.tasks.zzm.run(com.google.android.gms:play-services-tasks@@18.0.2:1)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:942)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7872)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
